-- ════════════════════════════════════════════════════════════════════
-- Distributor catalog seed (shared data — no tenant_id).
-- Generated by scripts/seed-distributor-catalog.mjs — do not edit by hand.
-- Apply AFTER 0006_kind_betty_brant.sql. Idempotent (ON CONFLICT DO NOTHING).
-- ════════════════════════════════════════════════════════════════════

INSERT INTO distributor_sources (slug, name) VALUES ('sanmar', 'SanMar') ON CONFLICT (slug) DO NOTHING;
INSERT INTO distributor_sources (slug, name) VALUES ('ssactivewear', 'S&S Activewear') ON CONFLICT (slug) DO NOTHING;

-- Gildan G500
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G500', 'Gildan', 'Heavy Cotton T-Shirt', 'Gildan G500 — Heavy Cotton T-Shirt', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G500-BLA-S', 2.60, 500),
    ('Black', '#1A1A1A', 'M', 'G500-BLA-M', 2.60, 500),
    ('Black', '#1A1A1A', 'L', 'G500-BLA-L', 2.60, 500),
    ('Black', '#1A1A1A', 'XL', 'G500-BLA-XL', 2.60, 500),
    ('Black', '#1A1A1A', '2XL', 'G500-BLA-2XL', 4.60, 500),
    ('Black', '#1A1A1A', '3XL', 'G500-BLA-3XL', 5.60, 500),
    ('White', '#FFFFFF', 'S', 'G500-WHI-S', 2.60, 500),
    ('White', '#FFFFFF', 'M', 'G500-WHI-M', 2.60, 500),
    ('White', '#FFFFFF', 'L', 'G500-WHI-L', 2.60, 500),
    ('White', '#FFFFFF', 'XL', 'G500-WHI-XL', 2.60, 500),
    ('White', '#FFFFFF', '2XL', 'G500-WHI-2XL', 4.60, 500),
    ('White', '#FFFFFF', '3XL', 'G500-WHI-3XL', 5.60, 500),
    ('Navy', '#1F2A44', 'S', 'G500-NAV-S', 2.60, 500),
    ('Navy', '#1F2A44', 'M', 'G500-NAV-M', 2.60, 500),
    ('Navy', '#1F2A44', 'L', 'G500-NAV-L', 2.60, 500),
    ('Navy', '#1F2A44', 'XL', 'G500-NAV-XL', 2.60, 500),
    ('Navy', '#1F2A44', '2XL', 'G500-NAV-2XL', 4.60, 500),
    ('Navy', '#1F2A44', '3XL', 'G500-NAV-3XL', 5.60, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G500'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G640
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G640', 'Gildan', 'Softstyle T-Shirt', 'Gildan G640 — Softstyle T-Shirt', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G640-BLA-S', 2.90, 500),
    ('Black', '#1A1A1A', 'M', 'G640-BLA-M', 2.90, 500),
    ('Black', '#1A1A1A', 'L', 'G640-BLA-L', 2.90, 500),
    ('Black', '#1A1A1A', 'XL', 'G640-BLA-XL', 2.90, 500),
    ('Black', '#1A1A1A', '2XL', 'G640-BLA-2XL', 4.90, 500),
    ('Black', '#1A1A1A', '3XL', 'G640-BLA-3XL', 5.90, 500),
    ('White', '#FFFFFF', 'S', 'G640-WHI-S', 2.90, 500),
    ('White', '#FFFFFF', 'M', 'G640-WHI-M', 2.90, 500),
    ('White', '#FFFFFF', 'L', 'G640-WHI-L', 2.90, 500),
    ('White', '#FFFFFF', 'XL', 'G640-WHI-XL', 2.90, 500),
    ('White', '#FFFFFF', '2XL', 'G640-WHI-2XL', 4.90, 500),
    ('White', '#FFFFFF', '3XL', 'G640-WHI-3XL', 5.90, 500),
    ('Navy', '#1F2A44', 'S', 'G640-NAV-S', 2.90, 500),
    ('Navy', '#1F2A44', 'M', 'G640-NAV-M', 2.90, 500),
    ('Navy', '#1F2A44', 'L', 'G640-NAV-L', 2.90, 500),
    ('Navy', '#1F2A44', 'XL', 'G640-NAV-XL', 2.90, 500),
    ('Navy', '#1F2A44', '2XL', 'G640-NAV-2XL', 4.90, 500),
    ('Navy', '#1F2A44', '3XL', 'G640-NAV-3XL', 5.90, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G640'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G800
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G800', 'Gildan', 'DryBlend T-Shirt', 'Gildan G800 — DryBlend T-Shirt', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G800-BLA-S', 2.80, 500),
    ('Black', '#1A1A1A', 'M', 'G800-BLA-M', 2.80, 500),
    ('Black', '#1A1A1A', 'L', 'G800-BLA-L', 2.80, 500),
    ('Black', '#1A1A1A', 'XL', 'G800-BLA-XL', 2.80, 500),
    ('Black', '#1A1A1A', '2XL', 'G800-BLA-2XL', 4.80, 500),
    ('Black', '#1A1A1A', '3XL', 'G800-BLA-3XL', 5.80, 500),
    ('White', '#FFFFFF', 'S', 'G800-WHI-S', 2.80, 500),
    ('White', '#FFFFFF', 'M', 'G800-WHI-M', 2.80, 500),
    ('White', '#FFFFFF', 'L', 'G800-WHI-L', 2.80, 500),
    ('White', '#FFFFFF', 'XL', 'G800-WHI-XL', 2.80, 500),
    ('White', '#FFFFFF', '2XL', 'G800-WHI-2XL', 4.80, 500),
    ('White', '#FFFFFF', '3XL', 'G800-WHI-3XL', 5.80, 500),
    ('Navy', '#1F2A44', 'S', 'G800-NAV-S', 2.80, 500),
    ('Navy', '#1F2A44', 'M', 'G800-NAV-M', 2.80, 500),
    ('Navy', '#1F2A44', 'L', 'G800-NAV-L', 2.80, 500),
    ('Navy', '#1F2A44', 'XL', 'G800-NAV-XL', 2.80, 500),
    ('Navy', '#1F2A44', '2XL', 'G800-NAV-2XL', 4.80, 500),
    ('Navy', '#1F2A44', '3XL', 'G800-NAV-3XL', 5.80, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G800'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G2000
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G2000', 'Gildan', 'Ultra Cotton T-Shirt', 'Gildan G2000 — Ultra Cotton T-Shirt', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G2000-BLA-S', 3.10, 500),
    ('Black', '#1A1A1A', 'M', 'G2000-BLA-M', 3.10, 500),
    ('Black', '#1A1A1A', 'L', 'G2000-BLA-L', 3.10, 500),
    ('Black', '#1A1A1A', 'XL', 'G2000-BLA-XL', 3.10, 500),
    ('Black', '#1A1A1A', '2XL', 'G2000-BLA-2XL', 5.10, 500),
    ('Black', '#1A1A1A', '3XL', 'G2000-BLA-3XL', 6.10, 500),
    ('White', '#FFFFFF', 'S', 'G2000-WHI-S', 3.10, 500),
    ('White', '#FFFFFF', 'M', 'G2000-WHI-M', 3.10, 500),
    ('White', '#FFFFFF', 'L', 'G2000-WHI-L', 3.10, 500),
    ('White', '#FFFFFF', 'XL', 'G2000-WHI-XL', 3.10, 500),
    ('White', '#FFFFFF', '2XL', 'G2000-WHI-2XL', 5.10, 500),
    ('White', '#FFFFFF', '3XL', 'G2000-WHI-3XL', 6.10, 500),
    ('Navy', '#1F2A44', 'S', 'G2000-NAV-S', 3.10, 500),
    ('Navy', '#1F2A44', 'M', 'G2000-NAV-M', 3.10, 500),
    ('Navy', '#1F2A44', 'L', 'G2000-NAV-L', 3.10, 500),
    ('Navy', '#1F2A44', 'XL', 'G2000-NAV-XL', 3.10, 500),
    ('Navy', '#1F2A44', '2XL', 'G2000-NAV-2XL', 5.10, 500),
    ('Navy', '#1F2A44', '3XL', 'G2000-NAV-3XL', 6.10, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G2000'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G185
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G185', 'Gildan', 'Heavy Blend Hooded Sweatshirt', 'Gildan G185 — Heavy Blend Hooded Sweatshirt', 'Hoodie'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G185-BLA-S', 9.50, 500),
    ('Black', '#1A1A1A', 'M', 'G185-BLA-M', 9.50, 500),
    ('Black', '#1A1A1A', 'L', 'G185-BLA-L', 9.50, 500),
    ('Black', '#1A1A1A', 'XL', 'G185-BLA-XL', 9.50, 500),
    ('Black', '#1A1A1A', '2XL', 'G185-BLA-2XL', 11.50, 500),
    ('Black', '#1A1A1A', '3XL', 'G185-BLA-3XL', 12.50, 500),
    ('White', '#FFFFFF', 'S', 'G185-WHI-S', 9.50, 500),
    ('White', '#FFFFFF', 'M', 'G185-WHI-M', 9.50, 500),
    ('White', '#FFFFFF', 'L', 'G185-WHI-L', 9.50, 500),
    ('White', '#FFFFFF', 'XL', 'G185-WHI-XL', 9.50, 500),
    ('White', '#FFFFFF', '2XL', 'G185-WHI-2XL', 11.50, 500),
    ('White', '#FFFFFF', '3XL', 'G185-WHI-3XL', 12.50, 500),
    ('Navy', '#1F2A44', 'S', 'G185-NAV-S', 9.50, 500),
    ('Navy', '#1F2A44', 'M', 'G185-NAV-M', 9.50, 500),
    ('Navy', '#1F2A44', 'L', 'G185-NAV-L', 9.50, 500),
    ('Navy', '#1F2A44', 'XL', 'G185-NAV-XL', 9.50, 500),
    ('Navy', '#1F2A44', '2XL', 'G185-NAV-2XL', 11.50, 500),
    ('Navy', '#1F2A44', '3XL', 'G185-NAV-3XL', 12.50, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G185'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G125
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G125', 'Gildan', 'DryBlend Crewneck Sweatshirt', 'Gildan G125 — DryBlend Crewneck Sweatshirt', 'Sweatshirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G125-BLA-S', 8.20, 500),
    ('Black', '#1A1A1A', 'M', 'G125-BLA-M', 8.20, 500),
    ('Black', '#1A1A1A', 'L', 'G125-BLA-L', 8.20, 500),
    ('Black', '#1A1A1A', 'XL', 'G125-BLA-XL', 8.20, 500),
    ('Black', '#1A1A1A', '2XL', 'G125-BLA-2XL', 10.20, 500),
    ('Black', '#1A1A1A', '3XL', 'G125-BLA-3XL', 11.20, 500),
    ('White', '#FFFFFF', 'S', 'G125-WHI-S', 8.20, 500),
    ('White', '#FFFFFF', 'M', 'G125-WHI-M', 8.20, 500),
    ('White', '#FFFFFF', 'L', 'G125-WHI-L', 8.20, 500),
    ('White', '#FFFFFF', 'XL', 'G125-WHI-XL', 8.20, 500),
    ('White', '#FFFFFF', '2XL', 'G125-WHI-2XL', 10.20, 500),
    ('White', '#FFFFFF', '3XL', 'G125-WHI-3XL', 11.20, 500),
    ('Navy', '#1F2A44', 'S', 'G125-NAV-S', 8.20, 500),
    ('Navy', '#1F2A44', 'M', 'G125-NAV-M', 8.20, 500),
    ('Navy', '#1F2A44', 'L', 'G125-NAV-L', 8.20, 500),
    ('Navy', '#1F2A44', 'XL', 'G125-NAV-XL', 8.20, 500),
    ('Navy', '#1F2A44', '2XL', 'G125-NAV-2XL', 10.20, 500),
    ('Navy', '#1F2A44', '3XL', 'G125-NAV-3XL', 11.20, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G125'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G180
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G180', 'Gildan', 'Heavy Blend Crewneck Sweatshirt', 'Gildan G180 — Heavy Blend Crewneck Sweatshirt', 'Sweatshirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G180-BLA-S', 8.60, 500),
    ('Black', '#1A1A1A', 'M', 'G180-BLA-M', 8.60, 500),
    ('Black', '#1A1A1A', 'L', 'G180-BLA-L', 8.60, 500),
    ('Black', '#1A1A1A', 'XL', 'G180-BLA-XL', 8.60, 500),
    ('Black', '#1A1A1A', '2XL', 'G180-BLA-2XL', 10.60, 500),
    ('Black', '#1A1A1A', '3XL', 'G180-BLA-3XL', 11.60, 500),
    ('White', '#FFFFFF', 'S', 'G180-WHI-S', 8.60, 500),
    ('White', '#FFFFFF', 'M', 'G180-WHI-M', 8.60, 500),
    ('White', '#FFFFFF', 'L', 'G180-WHI-L', 8.60, 500),
    ('White', '#FFFFFF', 'XL', 'G180-WHI-XL', 8.60, 500),
    ('White', '#FFFFFF', '2XL', 'G180-WHI-2XL', 10.60, 500),
    ('White', '#FFFFFF', '3XL', 'G180-WHI-3XL', 11.60, 500),
    ('Navy', '#1F2A44', 'S', 'G180-NAV-S', 8.60, 500),
    ('Navy', '#1F2A44', 'M', 'G180-NAV-M', 8.60, 500),
    ('Navy', '#1F2A44', 'L', 'G180-NAV-L', 8.60, 500),
    ('Navy', '#1F2A44', 'XL', 'G180-NAV-XL', 8.60, 500),
    ('Navy', '#1F2A44', '2XL', 'G180-NAV-2XL', 10.60, 500),
    ('Navy', '#1F2A44', '3XL', 'G180-NAV-3XL', 11.60, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G180'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G184
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G184', 'Gildan', 'Heavy Blend Full-Zip Hoodie', 'Gildan G184 — Heavy Blend Full-Zip Hoodie', 'Hoodie'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G184-BLA-S', 11.40, 500),
    ('Black', '#1A1A1A', 'M', 'G184-BLA-M', 11.40, 500),
    ('Black', '#1A1A1A', 'L', 'G184-BLA-L', 11.40, 500),
    ('Black', '#1A1A1A', 'XL', 'G184-BLA-XL', 11.40, 500),
    ('Black', '#1A1A1A', '2XL', 'G184-BLA-2XL', 13.40, 500),
    ('Black', '#1A1A1A', '3XL', 'G184-BLA-3XL', 14.40, 500),
    ('White', '#FFFFFF', 'S', 'G184-WHI-S', 11.40, 500),
    ('White', '#FFFFFF', 'M', 'G184-WHI-M', 11.40, 500),
    ('White', '#FFFFFF', 'L', 'G184-WHI-L', 11.40, 500),
    ('White', '#FFFFFF', 'XL', 'G184-WHI-XL', 11.40, 500),
    ('White', '#FFFFFF', '2XL', 'G184-WHI-2XL', 13.40, 500),
    ('White', '#FFFFFF', '3XL', 'G184-WHI-3XL', 14.40, 500),
    ('Navy', '#1F2A44', 'S', 'G184-NAV-S', 11.40, 500),
    ('Navy', '#1F2A44', 'M', 'G184-NAV-M', 11.40, 500),
    ('Navy', '#1F2A44', 'L', 'G184-NAV-L', 11.40, 500),
    ('Navy', '#1F2A44', 'XL', 'G184-NAV-XL', 11.40, 500),
    ('Navy', '#1F2A44', '2XL', 'G184-NAV-2XL', 13.40, 500),
    ('Navy', '#1F2A44', '3XL', 'G184-NAV-3XL', 14.40, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G184'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G470
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G470', 'Gildan', 'Performance Long Sleeve T-Shirt', 'Gildan G470 — Performance Long Sleeve T-Shirt', 'Long Sleeve'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G470-BLA-S', 5.20, 500),
    ('Black', '#1A1A1A', 'M', 'G470-BLA-M', 5.20, 500),
    ('Black', '#1A1A1A', 'L', 'G470-BLA-L', 5.20, 500),
    ('Black', '#1A1A1A', 'XL', 'G470-BLA-XL', 5.20, 500),
    ('Black', '#1A1A1A', '2XL', 'G470-BLA-2XL', 7.20, 500),
    ('Black', '#1A1A1A', '3XL', 'G470-BLA-3XL', 8.20, 500),
    ('White', '#FFFFFF', 'S', 'G470-WHI-S', 5.20, 500),
    ('White', '#FFFFFF', 'M', 'G470-WHI-M', 5.20, 500),
    ('White', '#FFFFFF', 'L', 'G470-WHI-L', 5.20, 500),
    ('White', '#FFFFFF', 'XL', 'G470-WHI-XL', 5.20, 500),
    ('White', '#FFFFFF', '2XL', 'G470-WHI-2XL', 7.20, 500),
    ('White', '#FFFFFF', '3XL', 'G470-WHI-3XL', 8.20, 500),
    ('Navy', '#1F2A44', 'S', 'G470-NAV-S', 5.20, 500),
    ('Navy', '#1F2A44', 'M', 'G470-NAV-M', 5.20, 500),
    ('Navy', '#1F2A44', 'L', 'G470-NAV-L', 5.20, 500),
    ('Navy', '#1F2A44', 'XL', 'G470-NAV-XL', 5.20, 500),
    ('Navy', '#1F2A44', '2XL', 'G470-NAV-2XL', 7.20, 500),
    ('Navy', '#1F2A44', '3XL', 'G470-NAV-3XL', 8.20, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G470'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G540
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G540', 'Gildan', 'Heavy Cotton Long Sleeve T-Shirt', 'Gildan G540 — Heavy Cotton Long Sleeve T-Shirt', 'Long Sleeve'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G540-BLA-S', 4.40, 500),
    ('Black', '#1A1A1A', 'M', 'G540-BLA-M', 4.40, 500),
    ('Black', '#1A1A1A', 'L', 'G540-BLA-L', 4.40, 500),
    ('Black', '#1A1A1A', 'XL', 'G540-BLA-XL', 4.40, 500),
    ('Black', '#1A1A1A', '2XL', 'G540-BLA-2XL', 6.40, 500),
    ('Black', '#1A1A1A', '3XL', 'G540-BLA-3XL', 7.40, 500),
    ('White', '#FFFFFF', 'S', 'G540-WHI-S', 4.40, 500),
    ('White', '#FFFFFF', 'M', 'G540-WHI-M', 4.40, 500),
    ('White', '#FFFFFF', 'L', 'G540-WHI-L', 4.40, 500),
    ('White', '#FFFFFF', 'XL', 'G540-WHI-XL', 4.40, 500),
    ('White', '#FFFFFF', '2XL', 'G540-WHI-2XL', 6.40, 500),
    ('White', '#FFFFFF', '3XL', 'G540-WHI-3XL', 7.40, 500),
    ('Navy', '#1F2A44', 'S', 'G540-NAV-S', 4.40, 500),
    ('Navy', '#1F2A44', 'M', 'G540-NAV-M', 4.40, 500),
    ('Navy', '#1F2A44', 'L', 'G540-NAV-L', 4.40, 500),
    ('Navy', '#1F2A44', 'XL', 'G540-NAV-XL', 4.40, 500),
    ('Navy', '#1F2A44', '2XL', 'G540-NAV-2XL', 6.40, 500),
    ('Navy', '#1F2A44', '3XL', 'G540-NAV-3XL', 7.40, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G540'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G420
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G420', 'Gildan', 'Performance Core T-Shirt', 'Gildan G420 — Performance Core T-Shirt', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G420-BLA-S', 3.40, 500),
    ('Black', '#1A1A1A', 'M', 'G420-BLA-M', 3.40, 500),
    ('Black', '#1A1A1A', 'L', 'G420-BLA-L', 3.40, 500),
    ('Black', '#1A1A1A', 'XL', 'G420-BLA-XL', 3.40, 500),
    ('Black', '#1A1A1A', '2XL', 'G420-BLA-2XL', 5.40, 500),
    ('Black', '#1A1A1A', '3XL', 'G420-BLA-3XL', 6.40, 500),
    ('White', '#FFFFFF', 'S', 'G420-WHI-S', 3.40, 500),
    ('White', '#FFFFFF', 'M', 'G420-WHI-M', 3.40, 500),
    ('White', '#FFFFFF', 'L', 'G420-WHI-L', 3.40, 500),
    ('White', '#FFFFFF', 'XL', 'G420-WHI-XL', 3.40, 500),
    ('White', '#FFFFFF', '2XL', 'G420-WHI-2XL', 5.40, 500),
    ('White', '#FFFFFF', '3XL', 'G420-WHI-3XL', 6.40, 500),
    ('Navy', '#1F2A44', 'S', 'G420-NAV-S', 3.40, 500),
    ('Navy', '#1F2A44', 'M', 'G420-NAV-M', 3.40, 500),
    ('Navy', '#1F2A44', 'L', 'G420-NAV-L', 3.40, 500),
    ('Navy', '#1F2A44', 'XL', 'G420-NAV-XL', 3.40, 500),
    ('Navy', '#1F2A44', '2XL', 'G420-NAV-2XL', 5.40, 500),
    ('Navy', '#1F2A44', '3XL', 'G420-NAV-3XL', 6.40, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G420'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Gildan G670
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, 'G670', 'Gildan', 'Performance Polo', 'Gildan G670 — Performance Polo', 'Polo'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', 'G670-BLA-S', 6.10, 500),
    ('Black', '#1A1A1A', 'M', 'G670-BLA-M', 6.10, 500),
    ('Black', '#1A1A1A', 'L', 'G670-BLA-L', 6.10, 500),
    ('Black', '#1A1A1A', 'XL', 'G670-BLA-XL', 6.10, 500),
    ('Black', '#1A1A1A', '2XL', 'G670-BLA-2XL', 8.10, 500),
    ('Black', '#1A1A1A', '3XL', 'G670-BLA-3XL', 9.10, 500),
    ('White', '#FFFFFF', 'S', 'G670-WHI-S', 6.10, 500),
    ('White', '#FFFFFF', 'M', 'G670-WHI-M', 6.10, 500),
    ('White', '#FFFFFF', 'L', 'G670-WHI-L', 6.10, 500),
    ('White', '#FFFFFF', 'XL', 'G670-WHI-XL', 6.10, 500),
    ('White', '#FFFFFF', '2XL', 'G670-WHI-2XL', 8.10, 500),
    ('White', '#FFFFFF', '3XL', 'G670-WHI-3XL', 9.10, 500),
    ('Navy', '#1F2A44', 'S', 'G670-NAV-S', 6.10, 500),
    ('Navy', '#1F2A44', 'M', 'G670-NAV-M', 6.10, 500),
    ('Navy', '#1F2A44', 'L', 'G670-NAV-L', 6.10, 500),
    ('Navy', '#1F2A44', 'XL', 'G670-NAV-XL', 6.10, 500),
    ('Navy', '#1F2A44', '2XL', 'G670-NAV-2XL', 8.10, 500),
    ('Navy', '#1F2A44', '3XL', 'G670-NAV-3XL', 9.10, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = 'G670'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Bella+Canvas 3001C
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '3001C', 'Bella+Canvas', 'Unisex Jersey Short Sleeve Tee', 'Bella+Canvas 3001C — Unisex Jersey Short Sleeve Tee', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '3001C-BLA-S', 3.60, 500),
    ('Black', '#1A1A1A', 'M', '3001C-BLA-M', 3.60, 500),
    ('Black', '#1A1A1A', 'L', '3001C-BLA-L', 3.60, 500),
    ('Black', '#1A1A1A', 'XL', '3001C-BLA-XL', 3.60, 500),
    ('Black', '#1A1A1A', '2XL', '3001C-BLA-2XL', 5.60, 500),
    ('Black', '#1A1A1A', '3XL', '3001C-BLA-3XL', 6.60, 500),
    ('White', '#FFFFFF', 'S', '3001C-WHI-S', 3.60, 500),
    ('White', '#FFFFFF', 'M', '3001C-WHI-M', 3.60, 500),
    ('White', '#FFFFFF', 'L', '3001C-WHI-L', 3.60, 500),
    ('White', '#FFFFFF', 'XL', '3001C-WHI-XL', 3.60, 500),
    ('White', '#FFFFFF', '2XL', '3001C-WHI-2XL', 5.60, 500),
    ('White', '#FFFFFF', '3XL', '3001C-WHI-3XL', 6.60, 500),
    ('Navy', '#1F2A44', 'S', '3001C-NAV-S', 3.60, 500),
    ('Navy', '#1F2A44', 'M', '3001C-NAV-M', 3.60, 500),
    ('Navy', '#1F2A44', 'L', '3001C-NAV-L', 3.60, 500),
    ('Navy', '#1F2A44', 'XL', '3001C-NAV-XL', 3.60, 500),
    ('Navy', '#1F2A44', '2XL', '3001C-NAV-2XL', 5.60, 500),
    ('Navy', '#1F2A44', '3XL', '3001C-NAV-3XL', 6.60, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '3001C'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Bella+Canvas 3001CVC
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '3001CVC', 'Bella+Canvas', 'Unisex Heather CVC Tee', 'Bella+Canvas 3001CVC — Unisex Heather CVC Tee', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '3001CVC-BLA-S', 4.00, 500),
    ('Black', '#1A1A1A', 'M', '3001CVC-BLA-M', 4.00, 500),
    ('Black', '#1A1A1A', 'L', '3001CVC-BLA-L', 4.00, 500),
    ('Black', '#1A1A1A', 'XL', '3001CVC-BLA-XL', 4.00, 500),
    ('Black', '#1A1A1A', '2XL', '3001CVC-BLA-2XL', 6.00, 500),
    ('Black', '#1A1A1A', '3XL', '3001CVC-BLA-3XL', 7.00, 500),
    ('White', '#FFFFFF', 'S', '3001CVC-WHI-S', 4.00, 500),
    ('White', '#FFFFFF', 'M', '3001CVC-WHI-M', 4.00, 500),
    ('White', '#FFFFFF', 'L', '3001CVC-WHI-L', 4.00, 500),
    ('White', '#FFFFFF', 'XL', '3001CVC-WHI-XL', 4.00, 500),
    ('White', '#FFFFFF', '2XL', '3001CVC-WHI-2XL', 6.00, 500),
    ('White', '#FFFFFF', '3XL', '3001CVC-WHI-3XL', 7.00, 500),
    ('Navy', '#1F2A44', 'S', '3001CVC-NAV-S', 4.00, 500),
    ('Navy', '#1F2A44', 'M', '3001CVC-NAV-M', 4.00, 500),
    ('Navy', '#1F2A44', 'L', '3001CVC-NAV-L', 4.00, 500),
    ('Navy', '#1F2A44', 'XL', '3001CVC-NAV-XL', 4.00, 500),
    ('Navy', '#1F2A44', '2XL', '3001CVC-NAV-2XL', 6.00, 500),
    ('Navy', '#1F2A44', '3XL', '3001CVC-NAV-3XL', 7.00, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '3001CVC'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Bella+Canvas 3413
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '3413', 'Bella+Canvas', 'Unisex Triblend Tee', 'Bella+Canvas 3413 — Unisex Triblend Tee', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '3413-BLA-S', 5.00, 500),
    ('Black', '#1A1A1A', 'M', '3413-BLA-M', 5.00, 500),
    ('Black', '#1A1A1A', 'L', '3413-BLA-L', 5.00, 500),
    ('Black', '#1A1A1A', 'XL', '3413-BLA-XL', 5.00, 500),
    ('Black', '#1A1A1A', '2XL', '3413-BLA-2XL', 7.00, 500),
    ('Black', '#1A1A1A', '3XL', '3413-BLA-3XL', 8.00, 500),
    ('White', '#FFFFFF', 'S', '3413-WHI-S', 5.00, 500),
    ('White', '#FFFFFF', 'M', '3413-WHI-M', 5.00, 500),
    ('White', '#FFFFFF', 'L', '3413-WHI-L', 5.00, 500),
    ('White', '#FFFFFF', 'XL', '3413-WHI-XL', 5.00, 500),
    ('White', '#FFFFFF', '2XL', '3413-WHI-2XL', 7.00, 500),
    ('White', '#FFFFFF', '3XL', '3413-WHI-3XL', 8.00, 500),
    ('Navy', '#1F2A44', 'S', '3413-NAV-S', 5.00, 500),
    ('Navy', '#1F2A44', 'M', '3413-NAV-M', 5.00, 500),
    ('Navy', '#1F2A44', 'L', '3413-NAV-L', 5.00, 500),
    ('Navy', '#1F2A44', 'XL', '3413-NAV-XL', 5.00, 500),
    ('Navy', '#1F2A44', '2XL', '3413-NAV-2XL', 7.00, 500),
    ('Navy', '#1F2A44', '3XL', '3413-NAV-3XL', 8.00, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '3413'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Bella+Canvas 3501
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '3501', 'Bella+Canvas', 'Unisex Long Sleeve Jersey Tee', 'Bella+Canvas 3501 — Unisex Long Sleeve Jersey Tee', 'Long Sleeve'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '3501-BLA-S', 6.20, 500),
    ('Black', '#1A1A1A', 'M', '3501-BLA-M', 6.20, 500),
    ('Black', '#1A1A1A', 'L', '3501-BLA-L', 6.20, 500),
    ('Black', '#1A1A1A', 'XL', '3501-BLA-XL', 6.20, 500),
    ('Black', '#1A1A1A', '2XL', '3501-BLA-2XL', 8.20, 500),
    ('Black', '#1A1A1A', '3XL', '3501-BLA-3XL', 9.20, 500),
    ('White', '#FFFFFF', 'S', '3501-WHI-S', 6.20, 500),
    ('White', '#FFFFFF', 'M', '3501-WHI-M', 6.20, 500),
    ('White', '#FFFFFF', 'L', '3501-WHI-L', 6.20, 500),
    ('White', '#FFFFFF', 'XL', '3501-WHI-XL', 6.20, 500),
    ('White', '#FFFFFF', '2XL', '3501-WHI-2XL', 8.20, 500),
    ('White', '#FFFFFF', '3XL', '3501-WHI-3XL', 9.20, 500),
    ('Navy', '#1F2A44', 'S', '3501-NAV-S', 6.20, 500),
    ('Navy', '#1F2A44', 'M', '3501-NAV-M', 6.20, 500),
    ('Navy', '#1F2A44', 'L', '3501-NAV-L', 6.20, 500),
    ('Navy', '#1F2A44', 'XL', '3501-NAV-XL', 6.20, 500),
    ('Navy', '#1F2A44', '2XL', '3501-NAV-2XL', 8.20, 500),
    ('Navy', '#1F2A44', '3XL', '3501-NAV-3XL', 9.20, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '3501'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Bella+Canvas 3719
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '3719', 'Bella+Canvas', 'Unisex Sponge Fleece Pullover Hoodie', 'Bella+Canvas 3719 — Unisex Sponge Fleece Pullover Hoodie', 'Hoodie'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '3719-BLA-S', 16.50, 500),
    ('Black', '#1A1A1A', 'M', '3719-BLA-M', 16.50, 500),
    ('Black', '#1A1A1A', 'L', '3719-BLA-L', 16.50, 500),
    ('Black', '#1A1A1A', 'XL', '3719-BLA-XL', 16.50, 500),
    ('Black', '#1A1A1A', '2XL', '3719-BLA-2XL', 18.50, 500),
    ('Black', '#1A1A1A', '3XL', '3719-BLA-3XL', 19.50, 500),
    ('White', '#FFFFFF', 'S', '3719-WHI-S', 16.50, 500),
    ('White', '#FFFFFF', 'M', '3719-WHI-M', 16.50, 500),
    ('White', '#FFFFFF', 'L', '3719-WHI-L', 16.50, 500),
    ('White', '#FFFFFF', 'XL', '3719-WHI-XL', 16.50, 500),
    ('White', '#FFFFFF', '2XL', '3719-WHI-2XL', 18.50, 500),
    ('White', '#FFFFFF', '3XL', '3719-WHI-3XL', 19.50, 500),
    ('Navy', '#1F2A44', 'S', '3719-NAV-S', 16.50, 500),
    ('Navy', '#1F2A44', 'M', '3719-NAV-M', 16.50, 500),
    ('Navy', '#1F2A44', 'L', '3719-NAV-L', 16.50, 500),
    ('Navy', '#1F2A44', 'XL', '3719-NAV-XL', 16.50, 500),
    ('Navy', '#1F2A44', '2XL', '3719-NAV-2XL', 18.50, 500),
    ('Navy', '#1F2A44', '3XL', '3719-NAV-3XL', 19.50, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '3719'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Bella+Canvas 3739
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '3739', 'Bella+Canvas', 'Unisex Sponge Fleece Full-Zip Hoodie', 'Bella+Canvas 3739 — Unisex Sponge Fleece Full-Zip Hoodie', 'Hoodie'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '3739-BLA-S', 19.00, 500),
    ('Black', '#1A1A1A', 'M', '3739-BLA-M', 19.00, 500),
    ('Black', '#1A1A1A', 'L', '3739-BLA-L', 19.00, 500),
    ('Black', '#1A1A1A', 'XL', '3739-BLA-XL', 19.00, 500),
    ('Black', '#1A1A1A', '2XL', '3739-BLA-2XL', 21.00, 500),
    ('Black', '#1A1A1A', '3XL', '3739-BLA-3XL', 22.00, 500),
    ('White', '#FFFFFF', 'S', '3739-WHI-S', 19.00, 500),
    ('White', '#FFFFFF', 'M', '3739-WHI-M', 19.00, 500),
    ('White', '#FFFFFF', 'L', '3739-WHI-L', 19.00, 500),
    ('White', '#FFFFFF', 'XL', '3739-WHI-XL', 19.00, 500),
    ('White', '#FFFFFF', '2XL', '3739-WHI-2XL', 21.00, 500),
    ('White', '#FFFFFF', '3XL', '3739-WHI-3XL', 22.00, 500),
    ('Navy', '#1F2A44', 'S', '3739-NAV-S', 19.00, 500),
    ('Navy', '#1F2A44', 'M', '3739-NAV-M', 19.00, 500),
    ('Navy', '#1F2A44', 'L', '3739-NAV-L', 19.00, 500),
    ('Navy', '#1F2A44', 'XL', '3739-NAV-XL', 19.00, 500),
    ('Navy', '#1F2A44', '2XL', '3739-NAV-2XL', 21.00, 500),
    ('Navy', '#1F2A44', '3XL', '3739-NAV-3XL', 22.00, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '3739'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Bella+Canvas 3945
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '3945', 'Bella+Canvas', 'Unisex Sponge Fleece Crewneck', 'Bella+Canvas 3945 — Unisex Sponge Fleece Crewneck', 'Sweatshirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '3945-BLA-S', 14.00, 500),
    ('Black', '#1A1A1A', 'M', '3945-BLA-M', 14.00, 500),
    ('Black', '#1A1A1A', 'L', '3945-BLA-L', 14.00, 500),
    ('Black', '#1A1A1A', 'XL', '3945-BLA-XL', 14.00, 500),
    ('Black', '#1A1A1A', '2XL', '3945-BLA-2XL', 16.00, 500),
    ('Black', '#1A1A1A', '3XL', '3945-BLA-3XL', 17.00, 500),
    ('White', '#FFFFFF', 'S', '3945-WHI-S', 14.00, 500),
    ('White', '#FFFFFF', 'M', '3945-WHI-M', 14.00, 500),
    ('White', '#FFFFFF', 'L', '3945-WHI-L', 14.00, 500),
    ('White', '#FFFFFF', 'XL', '3945-WHI-XL', 14.00, 500),
    ('White', '#FFFFFF', '2XL', '3945-WHI-2XL', 16.00, 500),
    ('White', '#FFFFFF', '3XL', '3945-WHI-3XL', 17.00, 500),
    ('Navy', '#1F2A44', 'S', '3945-NAV-S', 14.00, 500),
    ('Navy', '#1F2A44', 'M', '3945-NAV-M', 14.00, 500),
    ('Navy', '#1F2A44', 'L', '3945-NAV-L', 14.00, 500),
    ('Navy', '#1F2A44', 'XL', '3945-NAV-XL', 14.00, 500),
    ('Navy', '#1F2A44', '2XL', '3945-NAV-2XL', 16.00, 500),
    ('Navy', '#1F2A44', '3XL', '3945-NAV-3XL', 17.00, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '3945'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Bella+Canvas 6004
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '6004', 'Bella+Canvas', 'Women''s The Favorite Tee', 'Bella+Canvas 6004 — Women''s The Favorite Tee', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '6004-BLA-S', 3.80, 500),
    ('Black', '#1A1A1A', 'M', '6004-BLA-M', 3.80, 500),
    ('Black', '#1A1A1A', 'L', '6004-BLA-L', 3.80, 500),
    ('Black', '#1A1A1A', 'XL', '6004-BLA-XL', 3.80, 500),
    ('Black', '#1A1A1A', '2XL', '6004-BLA-2XL', 5.80, 500),
    ('Black', '#1A1A1A', '3XL', '6004-BLA-3XL', 6.80, 500),
    ('White', '#FFFFFF', 'S', '6004-WHI-S', 3.80, 500),
    ('White', '#FFFFFF', 'M', '6004-WHI-M', 3.80, 500),
    ('White', '#FFFFFF', 'L', '6004-WHI-L', 3.80, 500),
    ('White', '#FFFFFF', 'XL', '6004-WHI-XL', 3.80, 500),
    ('White', '#FFFFFF', '2XL', '6004-WHI-2XL', 5.80, 500),
    ('White', '#FFFFFF', '3XL', '6004-WHI-3XL', 6.80, 500),
    ('Navy', '#1F2A44', 'S', '6004-NAV-S', 3.80, 500),
    ('Navy', '#1F2A44', 'M', '6004-NAV-M', 3.80, 500),
    ('Navy', '#1F2A44', 'L', '6004-NAV-L', 3.80, 500),
    ('Navy', '#1F2A44', 'XL', '6004-NAV-XL', 3.80, 500),
    ('Navy', '#1F2A44', '2XL', '6004-NAV-2XL', 5.80, 500),
    ('Navy', '#1F2A44', '3XL', '6004-NAV-3XL', 6.80, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '6004'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Bella+Canvas 8800
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '8800', 'Bella+Canvas', 'Women''s Flowy Tank', 'Bella+Canvas 8800 — Women''s Flowy Tank', 'Tank'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '8800-BLA-S', 4.60, 500),
    ('Black', '#1A1A1A', 'M', '8800-BLA-M', 4.60, 500),
    ('Black', '#1A1A1A', 'L', '8800-BLA-L', 4.60, 500),
    ('Black', '#1A1A1A', 'XL', '8800-BLA-XL', 4.60, 500),
    ('Black', '#1A1A1A', '2XL', '8800-BLA-2XL', 6.60, 500),
    ('Black', '#1A1A1A', '3XL', '8800-BLA-3XL', 7.60, 500),
    ('White', '#FFFFFF', 'S', '8800-WHI-S', 4.60, 500),
    ('White', '#FFFFFF', 'M', '8800-WHI-M', 4.60, 500),
    ('White', '#FFFFFF', 'L', '8800-WHI-L', 4.60, 500),
    ('White', '#FFFFFF', 'XL', '8800-WHI-XL', 4.60, 500),
    ('White', '#FFFFFF', '2XL', '8800-WHI-2XL', 6.60, 500),
    ('White', '#FFFFFF', '3XL', '8800-WHI-3XL', 7.60, 500),
    ('Navy', '#1F2A44', 'S', '8800-NAV-S', 4.60, 500),
    ('Navy', '#1F2A44', 'M', '8800-NAV-M', 4.60, 500),
    ('Navy', '#1F2A44', 'L', '8800-NAV-L', 4.60, 500),
    ('Navy', '#1F2A44', 'XL', '8800-NAV-XL', 4.60, 500),
    ('Navy', '#1F2A44', '2XL', '8800-NAV-2XL', 6.60, 500),
    ('Navy', '#1F2A44', '3XL', '8800-NAV-3XL', 7.60, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '8800'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Bella+Canvas 3480
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '3480', 'Bella+Canvas', 'Unisex Jersey Tank', 'Bella+Canvas 3480 — Unisex Jersey Tank', 'Tank'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '3480-BLA-S', 3.50, 500),
    ('Black', '#1A1A1A', 'M', '3480-BLA-M', 3.50, 500),
    ('Black', '#1A1A1A', 'L', '3480-BLA-L', 3.50, 500),
    ('Black', '#1A1A1A', 'XL', '3480-BLA-XL', 3.50, 500),
    ('Black', '#1A1A1A', '2XL', '3480-BLA-2XL', 5.50, 500),
    ('Black', '#1A1A1A', '3XL', '3480-BLA-3XL', 6.50, 500),
    ('White', '#FFFFFF', 'S', '3480-WHI-S', 3.50, 500),
    ('White', '#FFFFFF', 'M', '3480-WHI-M', 3.50, 500),
    ('White', '#FFFFFF', 'L', '3480-WHI-L', 3.50, 500),
    ('White', '#FFFFFF', 'XL', '3480-WHI-XL', 3.50, 500),
    ('White', '#FFFFFF', '2XL', '3480-WHI-2XL', 5.50, 500),
    ('White', '#FFFFFF', '3XL', '3480-WHI-3XL', 6.50, 500),
    ('Navy', '#1F2A44', 'S', '3480-NAV-S', 3.50, 500),
    ('Navy', '#1F2A44', 'M', '3480-NAV-M', 3.50, 500),
    ('Navy', '#1F2A44', 'L', '3480-NAV-L', 3.50, 500),
    ('Navy', '#1F2A44', 'XL', '3480-NAV-XL', 3.50, 500),
    ('Navy', '#1F2A44', '2XL', '3480-NAV-2XL', 5.50, 500),
    ('Navy', '#1F2A44', '3XL', '3480-NAV-3XL', 6.50, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '3480'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Next Level 3600
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '3600', 'Next Level', 'Unisex Cotton Tee', 'Next Level 3600 — Unisex Cotton Tee', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '3600-BLA-S', 3.50, 500),
    ('Black', '#1A1A1A', 'M', '3600-BLA-M', 3.50, 500),
    ('Black', '#1A1A1A', 'L', '3600-BLA-L', 3.50, 500),
    ('Black', '#1A1A1A', 'XL', '3600-BLA-XL', 3.50, 500),
    ('Black', '#1A1A1A', '2XL', '3600-BLA-2XL', 5.50, 500),
    ('Black', '#1A1A1A', '3XL', '3600-BLA-3XL', 6.50, 500),
    ('White', '#FFFFFF', 'S', '3600-WHI-S', 3.50, 500),
    ('White', '#FFFFFF', 'M', '3600-WHI-M', 3.50, 500),
    ('White', '#FFFFFF', 'L', '3600-WHI-L', 3.50, 500),
    ('White', '#FFFFFF', 'XL', '3600-WHI-XL', 3.50, 500),
    ('White', '#FFFFFF', '2XL', '3600-WHI-2XL', 5.50, 500),
    ('White', '#FFFFFF', '3XL', '3600-WHI-3XL', 6.50, 500),
    ('Navy', '#1F2A44', 'S', '3600-NAV-S', 3.50, 500),
    ('Navy', '#1F2A44', 'M', '3600-NAV-M', 3.50, 500),
    ('Navy', '#1F2A44', 'L', '3600-NAV-L', 3.50, 500),
    ('Navy', '#1F2A44', 'XL', '3600-NAV-XL', 3.50, 500),
    ('Navy', '#1F2A44', '2XL', '3600-NAV-2XL', 5.50, 500),
    ('Navy', '#1F2A44', '3XL', '3600-NAV-3XL', 6.50, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '3600'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Next Level 6210
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '6210', 'Next Level', 'Unisex CVC Tee', 'Next Level 6210 — Unisex CVC Tee', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '6210-BLA-S', 3.90, 500),
    ('Black', '#1A1A1A', 'M', '6210-BLA-M', 3.90, 500),
    ('Black', '#1A1A1A', 'L', '6210-BLA-L', 3.90, 500),
    ('Black', '#1A1A1A', 'XL', '6210-BLA-XL', 3.90, 500),
    ('Black', '#1A1A1A', '2XL', '6210-BLA-2XL', 5.90, 500),
    ('Black', '#1A1A1A', '3XL', '6210-BLA-3XL', 6.90, 500),
    ('White', '#FFFFFF', 'S', '6210-WHI-S', 3.90, 500),
    ('White', '#FFFFFF', 'M', '6210-WHI-M', 3.90, 500),
    ('White', '#FFFFFF', 'L', '6210-WHI-L', 3.90, 500),
    ('White', '#FFFFFF', 'XL', '6210-WHI-XL', 3.90, 500),
    ('White', '#FFFFFF', '2XL', '6210-WHI-2XL', 5.90, 500),
    ('White', '#FFFFFF', '3XL', '6210-WHI-3XL', 6.90, 500),
    ('Navy', '#1F2A44', 'S', '6210-NAV-S', 3.90, 500),
    ('Navy', '#1F2A44', 'M', '6210-NAV-M', 3.90, 500),
    ('Navy', '#1F2A44', 'L', '6210-NAV-L', 3.90, 500),
    ('Navy', '#1F2A44', 'XL', '6210-NAV-XL', 3.90, 500),
    ('Navy', '#1F2A44', '2XL', '6210-NAV-2XL', 5.90, 500),
    ('Navy', '#1F2A44', '3XL', '6210-NAV-3XL', 6.90, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '6210'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Next Level 6010
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '6010', 'Next Level', 'Unisex Triblend Tee', 'Next Level 6010 — Unisex Triblend Tee', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '6010-BLA-S', 4.80, 500),
    ('Black', '#1A1A1A', 'M', '6010-BLA-M', 4.80, 500),
    ('Black', '#1A1A1A', 'L', '6010-BLA-L', 4.80, 500),
    ('Black', '#1A1A1A', 'XL', '6010-BLA-XL', 4.80, 500),
    ('Black', '#1A1A1A', '2XL', '6010-BLA-2XL', 6.80, 500),
    ('Black', '#1A1A1A', '3XL', '6010-BLA-3XL', 7.80, 500),
    ('White', '#FFFFFF', 'S', '6010-WHI-S', 4.80, 500),
    ('White', '#FFFFFF', 'M', '6010-WHI-M', 4.80, 500),
    ('White', '#FFFFFF', 'L', '6010-WHI-L', 4.80, 500),
    ('White', '#FFFFFF', 'XL', '6010-WHI-XL', 4.80, 500),
    ('White', '#FFFFFF', '2XL', '6010-WHI-2XL', 6.80, 500),
    ('White', '#FFFFFF', '3XL', '6010-WHI-3XL', 7.80, 500),
    ('Navy', '#1F2A44', 'S', '6010-NAV-S', 4.80, 500),
    ('Navy', '#1F2A44', 'M', '6010-NAV-M', 4.80, 500),
    ('Navy', '#1F2A44', 'L', '6010-NAV-L', 4.80, 500),
    ('Navy', '#1F2A44', 'XL', '6010-NAV-XL', 4.80, 500),
    ('Navy', '#1F2A44', '2XL', '6010-NAV-2XL', 6.80, 500),
    ('Navy', '#1F2A44', '3XL', '6010-NAV-3XL', 7.80, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '6010'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Next Level 6410
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '6410', 'Next Level', 'Unisex Sueded Tee', 'Next Level 6410 — Unisex Sueded Tee', 'T-Shirt'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '6410-BLA-S', 4.50, 500),
    ('Black', '#1A1A1A', 'M', '6410-BLA-M', 4.50, 500),
    ('Black', '#1A1A1A', 'L', '6410-BLA-L', 4.50, 500),
    ('Black', '#1A1A1A', 'XL', '6410-BLA-XL', 4.50, 500),
    ('Black', '#1A1A1A', '2XL', '6410-BLA-2XL', 6.50, 500),
    ('Black', '#1A1A1A', '3XL', '6410-BLA-3XL', 7.50, 500),
    ('White', '#FFFFFF', 'S', '6410-WHI-S', 4.50, 500),
    ('White', '#FFFFFF', 'M', '6410-WHI-M', 4.50, 500),
    ('White', '#FFFFFF', 'L', '6410-WHI-L', 4.50, 500),
    ('White', '#FFFFFF', 'XL', '6410-WHI-XL', 4.50, 500),
    ('White', '#FFFFFF', '2XL', '6410-WHI-2XL', 6.50, 500),
    ('White', '#FFFFFF', '3XL', '6410-WHI-3XL', 7.50, 500),
    ('Navy', '#1F2A44', 'S', '6410-NAV-S', 4.50, 500),
    ('Navy', '#1F2A44', 'M', '6410-NAV-M', 4.50, 500),
    ('Navy', '#1F2A44', 'L', '6410-NAV-L', 4.50, 500),
    ('Navy', '#1F2A44', 'XL', '6410-NAV-XL', 4.50, 500),
    ('Navy', '#1F2A44', '2XL', '6410-NAV-2XL', 6.50, 500),
    ('Navy', '#1F2A44', '3XL', '6410-NAV-3XL', 7.50, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '6410'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Next Level 3633
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '3633', 'Next Level', 'Unisex Long Sleeve Tee', 'Next Level 3633 — Unisex Long Sleeve Tee', 'Long Sleeve'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '3633-BLA-S', 5.60, 500),
    ('Black', '#1A1A1A', 'M', '3633-BLA-M', 5.60, 500),
    ('Black', '#1A1A1A', 'L', '3633-BLA-L', 5.60, 500),
    ('Black', '#1A1A1A', 'XL', '3633-BLA-XL', 5.60, 500),
    ('Black', '#1A1A1A', '2XL', '3633-BLA-2XL', 7.60, 500),
    ('Black', '#1A1A1A', '3XL', '3633-BLA-3XL', 8.60, 500),
    ('White', '#FFFFFF', 'S', '3633-WHI-S', 5.60, 500),
    ('White', '#FFFFFF', 'M', '3633-WHI-M', 5.60, 500),
    ('White', '#FFFFFF', 'L', '3633-WHI-L', 5.60, 500),
    ('White', '#FFFFFF', 'XL', '3633-WHI-XL', 5.60, 500),
    ('White', '#FFFFFF', '2XL', '3633-WHI-2XL', 7.60, 500),
    ('White', '#FFFFFF', '3XL', '3633-WHI-3XL', 8.60, 500),
    ('Navy', '#1F2A44', 'S', '3633-NAV-S', 5.60, 500),
    ('Navy', '#1F2A44', 'M', '3633-NAV-M', 5.60, 500),
    ('Navy', '#1F2A44', 'L', '3633-NAV-L', 5.60, 500),
    ('Navy', '#1F2A44', 'XL', '3633-NAV-XL', 5.60, 500),
    ('Navy', '#1F2A44', '2XL', '3633-NAV-2XL', 7.60, 500),
    ('Navy', '#1F2A44', '3XL', '3633-NAV-3XL', 8.60, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '3633'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Next Level 9001
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '9001', 'Next Level', 'Unisex French Terry Pullover Hoodie', 'Next Level 9001 — Unisex French Terry Pullover Hoodie', 'Hoodie'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '9001-BLA-S', 15.00, 500),
    ('Black', '#1A1A1A', 'M', '9001-BLA-M', 15.00, 500),
    ('Black', '#1A1A1A', 'L', '9001-BLA-L', 15.00, 500),
    ('Black', '#1A1A1A', 'XL', '9001-BLA-XL', 15.00, 500),
    ('Black', '#1A1A1A', '2XL', '9001-BLA-2XL', 17.00, 500),
    ('Black', '#1A1A1A', '3XL', '9001-BLA-3XL', 18.00, 500),
    ('White', '#FFFFFF', 'S', '9001-WHI-S', 15.00, 500),
    ('White', '#FFFFFF', 'M', '9001-WHI-M', 15.00, 500),
    ('White', '#FFFFFF', 'L', '9001-WHI-L', 15.00, 500),
    ('White', '#FFFFFF', 'XL', '9001-WHI-XL', 15.00, 500),
    ('White', '#FFFFFF', '2XL', '9001-WHI-2XL', 17.00, 500),
    ('White', '#FFFFFF', '3XL', '9001-WHI-3XL', 18.00, 500),
    ('Navy', '#1F2A44', 'S', '9001-NAV-S', 15.00, 500),
    ('Navy', '#1F2A44', 'M', '9001-NAV-M', 15.00, 500),
    ('Navy', '#1F2A44', 'L', '9001-NAV-L', 15.00, 500),
    ('Navy', '#1F2A44', 'XL', '9001-NAV-XL', 15.00, 500),
    ('Navy', '#1F2A44', '2XL', '9001-NAV-2XL', 17.00, 500),
    ('Navy', '#1F2A44', '3XL', '9001-NAV-3XL', 18.00, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '9001'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Next Level 9301
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '9301', 'Next Level', 'Unisex Sponge Fleece Pullover Hoodie', 'Next Level 9301 — Unisex Sponge Fleece Pullover Hoodie', 'Hoodie'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '9301-BLA-S', 15.80, 500),
    ('Black', '#1A1A1A', 'M', '9301-BLA-M', 15.80, 500),
    ('Black', '#1A1A1A', 'L', '9301-BLA-L', 15.80, 500),
    ('Black', '#1A1A1A', 'XL', '9301-BLA-XL', 15.80, 500),
    ('Black', '#1A1A1A', '2XL', '9301-BLA-2XL', 17.80, 500),
    ('Black', '#1A1A1A', '3XL', '9301-BLA-3XL', 18.80, 500),
    ('White', '#FFFFFF', 'S', '9301-WHI-S', 15.80, 500),
    ('White', '#FFFFFF', 'M', '9301-WHI-M', 15.80, 500),
    ('White', '#FFFFFF', 'L', '9301-WHI-L', 15.80, 500),
    ('White', '#FFFFFF', 'XL', '9301-WHI-XL', 15.80, 500),
    ('White', '#FFFFFF', '2XL', '9301-WHI-2XL', 17.80, 500),
    ('White', '#FFFFFF', '3XL', '9301-WHI-3XL', 18.80, 500),
    ('Navy', '#1F2A44', 'S', '9301-NAV-S', 15.80, 500),
    ('Navy', '#1F2A44', 'M', '9301-NAV-M', 15.80, 500),
    ('Navy', '#1F2A44', 'L', '9301-NAV-L', 15.80, 500),
    ('Navy', '#1F2A44', 'XL', '9301-NAV-XL', 15.80, 500),
    ('Navy', '#1F2A44', '2XL', '9301-NAV-2XL', 17.80, 500),
    ('Navy', '#1F2A44', '3XL', '9301-NAV-3XL', 18.80, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '9301'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Next Level 5030
INSERT INTO distributor_products (distributor_id, style_number, brand, name, description, category)
SELECT id, '5030', 'Next Level', 'Women''s Ideal Racerback Tank', 'Next Level 5030 — Women''s Ideal Racerback Tank', 'Tank'
FROM distributor_sources WHERE slug = 'sanmar'
ON CONFLICT (distributor_id, style_number) DO NOTHING;
INSERT INTO distributor_product_variants (distributor_product_id, color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
SELECT dp.id, v.color_name, v.color_hex, v.size_label, v.sku, v.wholesale_price, v.inventory_quantity
FROM distributor_products dp
JOIN distributor_sources ds ON ds.id = dp.distributor_id
CROSS JOIN (VALUES
    ('Black', '#1A1A1A', 'S', '5030-BLA-S', 4.20, 500),
    ('Black', '#1A1A1A', 'M', '5030-BLA-M', 4.20, 500),
    ('Black', '#1A1A1A', 'L', '5030-BLA-L', 4.20, 500),
    ('Black', '#1A1A1A', 'XL', '5030-BLA-XL', 4.20, 500),
    ('Black', '#1A1A1A', '2XL', '5030-BLA-2XL', 6.20, 500),
    ('Black', '#1A1A1A', '3XL', '5030-BLA-3XL', 7.20, 500),
    ('White', '#FFFFFF', 'S', '5030-WHI-S', 4.20, 500),
    ('White', '#FFFFFF', 'M', '5030-WHI-M', 4.20, 500),
    ('White', '#FFFFFF', 'L', '5030-WHI-L', 4.20, 500),
    ('White', '#FFFFFF', 'XL', '5030-WHI-XL', 4.20, 500),
    ('White', '#FFFFFF', '2XL', '5030-WHI-2XL', 6.20, 500),
    ('White', '#FFFFFF', '3XL', '5030-WHI-3XL', 7.20, 500),
    ('Navy', '#1F2A44', 'S', '5030-NAV-S', 4.20, 500),
    ('Navy', '#1F2A44', 'M', '5030-NAV-M', 4.20, 500),
    ('Navy', '#1F2A44', 'L', '5030-NAV-L', 4.20, 500),
    ('Navy', '#1F2A44', 'XL', '5030-NAV-XL', 4.20, 500),
    ('Navy', '#1F2A44', '2XL', '5030-NAV-2XL', 6.20, 500),
    ('Navy', '#1F2A44', '3XL', '5030-NAV-3XL', 7.20, 500)
) AS v(color_name, color_hex, size_label, sku, wholesale_price, inventory_quantity)
WHERE ds.slug = 'sanmar' AND dp.style_number = '5030'
ON CONFLICT (distributor_product_id, color_name, size_label) DO NOTHING;

-- Seeded 30 styles × 3 colors × 6 sizes = 540 variants.
